sudo: required

services:
- docker

env:
  global:
    - secure: QD2xge9rtP9uI0QVl+OSi7ZE4jVifJUC1gUW5mCiFkszdXB8Kck2qPEi3IKxGIXCK76p/xBiPRqZlGclNKA4MsmaaPlFiCZfRQKfvjaSnV1Fjz8l16HP8e+z0RGjek3efw4QBIvwr5izUhN+HcigOih6Ib0EK2TPGFEiwLKREYxLl4cP37Wz9JO7JVoXPcjJpjy22KC8G9wOMtXffikat04knYyMXoxbrXzY6Szp6UaZ3Hw63Phj177mZVtdS3iW3pXA+W6C40cFTPx9UkYgbS5bmtwr5FhN+n6gulrEThKxrX/jlDWGhNWUGYHOH1RDFGZLe8gpacQQRnwYA4eGXsLIfZsC1WSFLqVwNj8KpVX3OCStXSKaQk7b40+7tPgmKq6uqmLb9Xo6XdxX7YjRnp7oWJqUs+kogh9GcVvw7aGLzJIxabVxG4MFb+nAWlDLslZ9OtRPGy+Q2RfXYW7pWAY/l3fffBXJKWVXmFJZO/iaRPEK/H8Sk6e7CKUcImvdOYWD7nIuygftEHgphZnKmPHM4pGO8SZSFAHkqZzDtLhrUhbjqDJuZzZG2rMHXucIoy8FtbuW3/RJpSmbwenTaKr4rgUxsOkn8KwGqBkRdvG3oALnST2IwbruQokPo1QwpYDFMcRwefwKt0/hDIcvrHjFgDAcoRdT9L3gecPKklw=
    - secure: FK4AFIsbbdWCYLUmEZt91NFqcUb7Q/s6vq5y7caAITtH4V8FX1TpxvTD/4FyuWop0SR0SzzarnfBICAAFtVyU+ZcDlsV9qffIknxOcMkthcXZXie+WixTKm4T7kp06mKQMItOAYKGUb+zXLHlKc27PUGMqtXCmpnwoWGuWAoXu2QdXsK+pbWJ/EL8WsTFtMLudLKnohATc+IhSCjXhZGE0EQ6t8ciSNtr9I2d91BEeLelOc8nnvaQdcghO9Dt+xUJpt3ecoWBwheb3F4g00IBjX8Zy+TYfuz/HLShgi4GI3k7Ud8/k8fATXwQgQWOgd6/toFU9qRkWDS1iooXRjtlzdmQDdxPp0IbTX71HxGpGbT40MV+M7niU/ILDYJxZCgW2BLxZD3ymS6qq4vZr8WXpTo6aGOY5jCwdnzrgJMH1J0KxSdtFFZHhb9cc11TwCIB+dR70jgmpVlLT5SvGM3c5msk4evhh6HCmwnaCB4Mq5QOfh+IcYcZlWCXW2M0dvpJwbPJPAPEjjYPaaybQugX5fH/SVMhIZwTOFrH+81RE3x8ZxDxipL13HvjJz5h0ZIM+3GYVpbV5F5UJ7yXZS3Npj8n5yK2DvOa2nFc5l7WvbJm5LM7mo9vNlholAHvmaoa8rZsx7ETtzPnM98PMEwXZaOy0FqLhOskr4JR3oOslg=
    - COMMIT=${TRAVIS_COMMIT::8}

script:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=tercen/dartrusttidy
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
- docker build -f Dockerfile -t $REPO:$COMMIT .
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
